version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    expose :
      - 3306
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_vol:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    expose :
      - 9000
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www

networks:
  inception:
      driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/mariadb_vol
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/wordpress_vol
      o: bind